
#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.0.{build}


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  UnitTest: true

# enable service required for build/tests
services:
  - mssql2014           # start SQL Server 2014 Express


#---------------------------------#
#       build configuration       #
#---------------------------------#
    
# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  project: src\BuildScripts\build.proj
  verbosity: Diagnostic

  
  
#---------------------------------#
#       tests configuration       #
#---------------------------------#
test: off


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#


#---------------------------------#
#     deployment configuration    #
#---------------------------------#


#---------------------------------#
#        global handlers          #
#---------------------------------#


#---------------------------------#
#         notifications           #
#---------------------------------#